nome = str(input("Entre com nome"))
endereço = str(input("Entre com endereço"))
telefone = str(input("Entre com telefone"))
print("")
print("Nome: ", nome)
print("Endereço", endereço)
print("telefone: ", telefone)